### ISSUE TITLE
/usr/bin/env: ‘python2’: No such file or directory

### ISSUE THREAD

**Issue by slambrechts** [alexmsalmeida/virsearch#1]
Hi,

Thanks for sharing this pipeline! I seem to get some `/usr/bin/env: ‘python2’: No such file or directory` errors while running `snakemake --use-conda -k -j 48`. I'm guessing this has something to do with the configuration of python, snakemake or conda on our HPC? This does not happen with my other snakemake pipelines. Can I ask what snakemake version you use for this pipeline?

Best,
Sam

**Comment by alexmsalmeida** [comment]
Hi Sam, no problem!

I am almost certain this is due to the `rename_multifasta_prefix.py` script. I changed it to be compatible with python3 by default. Either reclone the repo or just replace that script with the new version. Let me know if you encounter further issues.

For future reference, I am using v6.3.0 of Snakemake.

Best,
Alex

**Comment by slambrechts** [comment]
Hi Alex,

Yes, I think you are right! After recloning the repo, this error did not appear again. Thank you!

Best,
Sam
